# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e384c2012ef4cdfccd3f24944554fac966c2355ce679682aeef1e90db17c891a456928bf407188b638fa84e1efc60a90179fb507b20b3a119b720a7ed7e84f2

test:
  secret_key_base: 6a603a0a2d600a84023b194a4f8437549bd47ba3272aa2ae41f7cacf80db3bc46df46d61960023739b358803c5776252950e2a908563f5a4313951c8f8cc35ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
